### ISSUE TITLE
create development branch someone else starts contributing

### ISSUE THREAD

**Issue by nyxnor** [nyxnor/tor-ctrl#7]
lot of changes on the script in past commit, create a dev branch when it is need.

**Comment by nyxnor** [comment]
@adrelanos if you feel it is needed, let me know.

**Comment by adrelanos** [comment]
No, I don't see much need for it right now.

Changes are usually small, non-controversial. So easy to merge into master branch. This is a small code base, which is a feature, not a bug. I don't think enough development happening to warrant a stable and different development branch.

If someone wants another branch in their repository they won't have write access here anyhow.

The question is, since you're upstream here, do you think you need to have a development branch and merge things there, test over some time and only then merge into master? If not, then no need. If you have a development branch, then a stable branch is a kind of "service" being provided to those who want to stay on stable. I don't see that kind of complexity here and that's a good thing for change.

**Comment by nyxnor** [comment]
thank you for the detailed explanation.

> The question is, since you're upstream here, do you think you need to have a development branch and merge things there, test over some time and only then merge into master? 

No. I test locally before pushing, just in case you made a big change, although merging conflicts should be easy to solve in this small codebase.
